site_name: Docodylus<br/>Developer Documentation
site_url: https://IainDavis-dev.github.io/docodylus/

plugins:
  - search
  - macros

markdown_extensions:
  - attr_list

theme:
  name: material

nav:
  - Overview:
    - About Docodylus: ./index.md
    - Tech Stack: ./overview/tech-stack.md
    - Code Organization: ./overview/code-organization.md
  - Contributing:
    - Getting Started: ./contributing/gettingStarted.md
    - Code Standards: ./contributing/code-standards.md
    - PR Expectations: ./contributing/pull-request-expectations.md
  - Testing: 
    - Unit Testing: ./testing/unit-tests.md
  - Infra: 
    - Build: ./infra/build.md
    - Release: ./infra/deploy.md
  - Architecture Decisions:
    - "ADR 0001": ./adr/0001-define-adr-structure-and-format-for-project.md
