name: Version Bump

on: 
    push:
        branches:
            - main
            - prerelease

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                fetch-depth: 0 # required for semantic-release to analyze commit history
            
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version-file: .nvmrc
            
            - name: Install dependencies
              run: yarn install --frozen-lockfile
            
            - name: Run Semantic Release
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: pwd && yarn semantic-release --extends infra/build/release/semantic-release.config.js